import { useRouter } from "next/router";
import { useState } from "react";
import axios from "axios";
import Head from "next/head";
import NavBar from "@/components/navbar";
import { authOptions } from './api/auth/[...nextauth]'
import { getServerSession } from "next-auth/next"
import EditingPost from "@/components/editingPost";

export default function NewPost(){
    const r = useRouter()
    const [errorMessage, setErrorMessage] = useState("")


    const submitData = async (formData) => {
        console.log(formData)
        if(formData.category == ""){
            setErrorMessage("Error: Must select a category!")
            return
        } else {
            setErrorMessage("")
        }
        const res = await axios.post('/api/posts', { 
            title: formData.title,
            content: formData.content,
            category: formData.category
        })
        
        r.push("/")
    }
    return(
        <>
            <Head>
                <title>CodeTipsTricks - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/codetipstricks.svg" />
            </Head>
            <NavBar onClickSignIn={()=>signIn()} onClickSignOut={()=>setForm("signOut")} />
            <main>
                <EditingPost childParent={submitData} creatingPost={true} cancelButton={()=>{r.push("/")}} />
                
                {errorMessage && <div>
                    {errorMessage}
                </div>}
            </main>
        </>
    )
}

export async function getServerSideProps(context){
    const session = await getServerSession(context.req, context.res, authOptions)
    if(!session){
        return{
            redirect:{
                destination: "/api/auth/signin",
                permanent:false
            }
        }
    }
    return{
        props:{
            session
        }
    }
  }